### ISSUE TITLE
EZABL Configuration.h is not configured correctly

### ISSUE THREAD

**Issue by ashefpv** [mriscoc/Special_Configurations#10]
In the "Ender3V2 4.2.2 configuration files" from 2022-05-27 located here https://github.com/mriscoc/Special_Configurations/releases the Configuration.h file has:
#define Z_MIN_ENDSTOP_INVERTING false

But according to https://www.th3dstudio.com/hc/product-information/ezabl/advanced-setup/ezabl-firmware-setup-for-vanilla-marlin/ it should be:
#define Z_MIN_ENDSTOP_INVERTING true

Once I updated that value to "true" in the Configuration.h file and compiled the EZABL sensor started working as expected.

**Comment by mriscoc** [comment]
V2 EZABL configurations updated
