### ISSUE TITLE
Ender 3 v2 4.2.2 neopixel support?

### ISSUE THREAD

**Issue by G1t1t** [mriscoc/Special_Configurations#11]
The 'mriscoc/Special_Configurations' repository doesn't contain the 'Ender3V2-422BLT-NEOGRB' path in 'main'

I can not get neopixels to function or get a menu for them?

**Comment by mriscoc** [comment]
Ender3V2-422BLT-NEOGRB is now Ender3V2-422-BLT-NEOGRB
Please verify the value of NEOPIXEL_PIN.
What pin are you using?

**Comment by mriscoc** [comment]
No more feedback
