### ISSUE TITLE
Standard configuration does not support 300°C by default

### ISSUE THREAD

**Issue by MathyCry** [mriscoc/Special_Configurations#14]
Hello, I successfully flashed this firmware onto my board. But can only set 260 degrees.

**Comment by xx1180** [comment]
https://www.youtube.com/watch?v=LyU2DCCP5Is&t=95s
watch this video it explains what you need to do it worked for me but please remember that after running this you need to store the settings or when you turn off it will revert back to max 260c

**Comment by mriscoc** [comment]
CAUTION!. Be sure that your hot-end really supports 300°C and there isn't any PTFE in any place (as terminal isolators for the thermistor for example)

**Comment by mriscoc** [comment]
Because this is not a firmware error, I will close this issue.

**Comment by MathyCry** [comment]
I followed the instructions from the video. But it doesn't work. I can still only set it to 260°C

**Comment by xx1180** [comment]
did you use notepad++ or just notepad

**Comment by MathyCry** [comment]
OS X TextEdit I used

**Comment by MathyCry** [comment]
Sorry, I found the error. Thank you very much for your help, you are great.
