### ISSUE TITLE
Ender 3V2 SKR Mini E3V3 Full Featured w/ Linear Advance

### ISSUE THREAD

**Issue by mriscoc** [mriscoc/Special_Configurations#15]
This is a first attempt to test Linear Advance activation for the Ender3 V2 with a SKR Mini E3V3 control board. It will use the following additional configuration:

```json
{
"Configuration.h" : [
  {
    "op": "Disable",
    "searchfor": "CLASSIC_JERK"
  },
  {
    "op": "CustomVal",
    "searchfor": "JUNCTION_DEVIATION_MM",
    "value": "0.1"
  }  
],
"Configuration_adv.h" : [
  {
    "op": "Enable",
    "searchfor": "LIN_ADVANCE"
  },
  {
    "op": "Disable",
    "searchfor": "S_CURVE_ACCELERATION"
  }
],
"Version.h" : [
]   
}
```

Generated configuration files are here: https://github.com/mriscoc/Special_Configurations/tree/main/Ender3V2-SKRME3V3-BLTUBL-LA

**Comment by jeeltuss** [comment]
Would it be possible to have a precompiled version among the special releases listed here https://github.com/mriscoc/Special_Configurations/releases/tag/LinearAdvance for the S1 with the F4 chip?

Thank you.

**Comment by mriscoc** [comment]
It's possible, but it requires work because LA doesn't fit inside F4 with normal firmware functions enabled. You must disable some features according to your preferences.

**Comment by SorenRR** [comment]
> It's possible, but it requires work because LA doesn't fit inside F4 with normal firmware functions enabled. You must disable some features according to your preferences.

Maybe make LA available for 512K versions only. Then people can either do a custom build or source a RET6 board.
Is there a way to fail upgrade with a message if trying to load 512K code on to a 256K board?

**Comment by mriscoc** [comment]
> Maybe make LA available for 512K versions only. Then people can either do a custom build or source a RET6 board. Is there a way to fail upgrade with a message if trying to load 512K code on to a 256K board?

According to what I know, there is not a stock F4 board with a RET6 (512) chip. Could be dangerous post a public binary only for RET6 chips. Users make mistakes all the time confusing boards. More easy is allow to any one to compile his own custom version.

Said that, sponsors can request custom private builds.

**Comment by SorenRR** [comment]
> > Maybe make LA available for 512K versions only. Then people can either do a custom build or source a RET6 board. Is there a way to fail upgrade with a message if trying to load 512K code on to a 256K board?
> 
> According to what I know, there is not a stock F4 board with a RET6 (512) chip. Could be dangerous post a public binary only for RET6 chips. Users make mistakes all the time confusing boards. More easy is allow to any one to compile his own custom version.
> 
> Said that, sponsors can request custom private builds.

Oh, missed that it's a SKR subject. I have a 4.2.2 RET6 board - different subject ;-)

**Comment by mriscoc** [comment]
> Oh, missed that it's a SKR subject. I have a 4.2.2 RET6 board - different subject ;-)
For 4.2.2: https://github.com/mriscoc/Special_Configurations/releases/tag/LinearAdvance

**Comment by SorenRR** [comment]
> > Oh, missed that it's a SKR subject. I have a 4.2.2 RET6 board - different subject ;-)
> 
> For 4.2.2: https://github.com/mriscoc/Special_Configurations/releases/tag/LinearAdvance

Yeah ;-) Thanks.
