### ISSUE TITLE
Ender3V2-427-BLTUBL-LA-20221002.bin not loading

### ISSUE THREAD

**Issue by Zyzzbarth333** [mriscoc/Special_Configurations#18]
Hi there, Ender3V2-427-BLTUBL-LA-20221002.bin, seems to give a blank screen when trying to laod it onto my printer, I reloaded current version of ENDER3V2-427-BLTUBL and works fine.

**Comment by SargFowler** [comment]
I can confirm the same issue. The bed gets hot and the temp runs away - mine got up to 100c.
The non LA version works fine.

**Comment by mriscoc** [comment]
Rename the firmware to a shorter name, change the filename between attempts.

**Comment by SargFowler** [comment]
Thanks for the reply. I've tried what you've suggested, but the BL just clicks away and there's no display. Other version works fine. How can I help to diagnose the fault?

**Comment by mriscoc** [comment]
Please test this: https://github.com/mriscoc/Special_Configurations/releases/download/LinearAdvance/Ender3V2-427-BLTUBL-LA-20221019.bin

**Comment by SargFowler** [comment]
Fabulous, that loads and runs OK. Just need to tune in the values to get the best print.
Thanks Miguel

**Comment by Zyzzbarth333** [comment]
Thank you Miguel! Works perfectly now!

**Comment by mriscoc** [comment]
Thank you for the confirmation.
