### ISSUE TITLE
Ender3V2_SKRMINIE3V3 Auto Shutdown Relay

### ISSUE THREAD

**Issue by gsuresh2u** [mriscoc/Special_Configurations#20]
Hi, i have downloaded Ender3V2-SKRME3V3-BLTUBL-20221002.bin for my Ender3V2 changed board
firmware upgraded fine and printing is also fine
Now i have added Auto shutdown Relay 1.2 from  BTT
Is there any option in screen menus to enable it ?
I am already using your screen firmware also, but not found anywhere
Afrer adding BTT Auto Shutdown relay, printer is automatically shutting off after 15 sec aftr powered On
Please help

**Comment by mriscoc** [comment]
No, that function is not enabled in standard firmware, it must be enabled in a custom build.
