### ISSUE TITLE
Cant compile LA +UBL for Ender3S1 301F4

### ISSUE THREAD

**Issue by StrangeAlex3003** [mriscoc/Special_Configurations#22]
**Describe the bug**
Unable to compile firmware for E3S1 301F4+LA+UBL. The firmware is too big for F4. 

**To Reproduce**
1. Configure by Configurator.pyw E3S1+301F4+BLT(UBL)+T1+LA
2. Compile by VSCode
3. See error

**Expected behavior**
LA is what you change the stock firmware for.  CR-touch is a necessary feature for printing on Ender3S1. Is it possible to cut something out of the firmware to keep these two functions, but everything fits into the memory of the 301F4?

**Screenshots**
c:/users/arusa/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/STM32F401RC_creality/firmware-20221204-191256.elf section `.rodata' will not fit in region `FLASH'
c:/users/arusa/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: region `FLASH' overflowed by 13136 bytes
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\STM32F401RC_creality\firmware-20221204-191256.elf] Error 1
======================= [FAILED] Took 230.95 seconds =======================

Environment           Status    Duration
--------------------  --------  ------------
STM32F401RC_creality  FAILED    00:03:50.954
=================== 1 failed, 0 succeeded in 00:03:50.954 ===================

**Comment by mriscoc** [comment]
The limited program memory of the F4 doesn't allow to enable UBL with the other features, so, each one must compile his own version disabling the features that do not need.
