### ISSUE TITLE
request a ender3v2-422-BLTUBL with  sprite extruder

### ISSUE THREAD

**Issue by liuxyc** [mriscoc/Special_Configurations#29]
config request:

ender3v2
422 motherboard
BLTouch + UBL
use sprite extruder full metal 300C extruder

**Comment by mriscoc** [comment]
Use the T13 version for Sprite Extruder Pro https://github.com/mriscoc/Special_Configurations/releases/tag/T13

**Comment by liuxyc** [comment]
there may not only hotend config need change but also some extruder step，probe offset,  mesh min/max X/Y  need change

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides
