### ISSUE TITLE
Support for SKR MINI E3 V2/V3.0

### ISSUE THREAD

**Issue by V1ntex** [mriscoc/Special_Configurations#3]
Hello!

Can anyone help correct the config files for SKR E3 Mini V3.0

I'm trying to build but I'm getting an error. 
![image](https://user-images.githubusercontent.com/32096887/150703048-6fb8d0f6-1b07-4c13-9f91-17afd30c4acd.jpeg)

**Comment by mriscoc** [comment]
Last version has support for the SKR MINI E3 V3 board
