### ISSUE TITLE
Support for Adafruit Neopixels - Digital RGB LEDs

### ISSUE THREAD

**Issue by mriscoc** [mriscoc/Special_Configurations#6]
Preliminary support for Adafruit Neopixels - Digital RGB LEDs

**Important** Set the NEOPIXEL_PIN to suit your mainboard.

https://teachingtechyt.github.io/upgrades.html#neopixels

```json
{
"Configuration_adv.h" : [
],
"Configuration.h" : [
  {
    "op": "Enable",
    "searchfor": "NEOPIXEL_LED",
    "comment": "Adafruit Neopixels"
  },
  {
    "op": "Custom",
    "searchfor": "NEOPIXEL_TYPE",
    "mask" : ".*",
    "value": "NEO_GRB",
    "comment": "Adafruit Neopixels"
  },
  {
    "op": "Custom",
    "searchfor": "NEOPIXEL_PIN",
    "mask" : ".*",
    "value": "PB2",
    "comment": "Adafruit Neopixels"
  },
  {
    "op": "CustomVal",
    "searchfor": "NEOPIXEL_PIXELS",
    "value": "15",
    "comment": "Adafruit Neopixels"
  },
  {
    "op": "Enable",
    "searchfor": "NEOPIXEL_STARTUP_TEST",
    "comment": "Adafruit Neopixels"
  }
],
"Version.h" : [
]   
}
```

https://youtu.be/SNAepJUDlsA

**Comment by Nbrooks639** [comment]
if adding neopixels to the ENDER 3 S1 you only have two pins that are open and not sharing with something else.

![image](https://user-images.githubusercontent.com/100983669/161349500-8acf888c-2d7c-4a56-a27d-b9f15b8e61dc.png)

you also cannot use the expansion connection behind z stepper motor. power needs to come from power supply and be stepped down to 5v via buck convertor or step down regulator. 
the led control menu will not work in this firmware so you need to enable EVENT_PRINTER_LIGHTS

**Comment by mriscoc** [comment]
> if adding neopixels to the ENDER 3 S1 you only have two pins that are open and not sharing with something else.
> 
The Neopixel uses one pin for data, are you using the PA13 pin?  For what is PA14?

**Comment by Nbrooks639** [comment]
you have the option to use either PA13 or PA14 for the data pin. sorry i should have specified that. either one with work as long as you change in configs.

**Comment by mriscoc** [comment]
Thanks for the info. I'm going to merge the light control menu already added to the ProUI configuration in the official Marlin repository, but it will not be enabled by default, if you compile the firmware you must enabled to use it.

**Comment by Nbrooks639** [comment]
Cool. I'm glad you decide this after I have already done it all lol. Sent from my T-Mobile 5G Device
-------- Original message --------From: Miguel Risco-Castillo ***@***.***> Date: 4/1/22  10:08 PM  (GMT-05:00) To: mriscoc/Marlin_Configurations ***@***.***> Cc: Nbrooks639 ***@***.***>, Comment ***@***.***> Subject: Re: [mriscoc/Marlin_Configurations] Support for Adafruit Neopixels - Digital RGB LEDs (Issue #6) 
Thanks for the info. I'm going to merge the light control menu already added to the ProUI configuration in the official Marlin repository, but it will not be enabled by default, if you compile the firmware you must enabled to use it.
